### ISSUE TITLE
"About Me" voltage differs from battery indicator

### ISSUE THREAD

**Issue by seth10** [mindsensors/PiStorms#7]

**Comment by seth10** [comment]
Both trace back to the same PiStormsCom.battVoltage method

# Call stacks

## About Me program

`psm = PiStorms()`
...
[`voltVal = psm.battVoltage()`](https://github.com/mindsensors/PiStorms/blob/master/programs/00-About_Me.py#L67)
`psm.screen.termPrintAt(5," Battery :     "   + str(voltVal)+"V" )`

## PiStorms

`self.psc = PiStormsCom()`
...
[`def battVoltage(self):`](https://github.com/mindsensors/PiStorms/blob/master/sys/PiStorms.py#L845)
`return self.psc.battVoltage()`

## PiStormsCom

`bankA = mindsensors_i2c(PS_A_ADDRESS >> 1)`
...
[`def battVoltage(self):`](https://github.com/mindsensors/PiStorms/blob/master/sys/PiStormsCom.py#L711)
    `try:`
        `return self.bankA.readByte(self.PS_BattV)*.040`
...

## Battery indicator

[`battVoltage = PiStormsCom().battVoltage()`](https://github.com/mindsensors/PiStorms/blob/master/sys/MSBrowser.py#L163)
...
`scrn.drawAutoText(("%1.1f V" if battVoltage < 10 else "%2.0f V") % battVoltage, 281, 213, size=16, display=False)`

**Comment by rbohuk** [comment]
This is because the voltages refresh at different rates. The measurement on the web interface updates every second whereas the reading on the indicator seems to update only when the user does something to force the screen to refresh (such as going to the next page).  The measurements are not perfect, and they fluctuate, which can at random make the voltages differ.

As a possible solution, there could be some form of memory to average the past three or so measurements either in the battery voltage method or both of the programs that use the indicator. Another possible solution would be to force the MSBrowser to update automatically every few seconds (maybe have a countdown in the `while (True)` loop). This will also allow the programs to be refreshed without having to run the refresh script.
